---
title: "Proposal"
output: github_document
---

**Group members:** 
Rhea Pawar (rp3022), Sneha Mehta (sm5134), Sophia Chkonia (sc4934), Shivangi Mewada (sm4956), Cathy Yang (my2731)

**Title:** 
Female Representation in Film: Does Girl Power Translate to Profit 

**Motivation For the project:**
"The Bechdel Test is a simple and popular measure of feminism in works of fiction. The rules of the test were first defined back in 1985 in a comic strip featuring two queer women who could not find a movie that:
Has at least two women in it,
who talk to each other,
about something other than a man.
It is an indicator of the active presence of women in the entire field of film and other fiction and calls attention to gender inequality in fiction. Some studies indicate that films that pass the test perform better financially while receiving a lower budget, compared to those that do not. Thus, through this project, we intend:
To examine the relationship between representation in movies and movie budget/profit
To examine the number of movies that pass the Bechdel test over time (2000 - 2020)
Examine this correlation with key time points in film history. 

**Intended final products:** 

 * Trend of Bechdel test scores for movies by year from 2000 to 2020
 * Relationship between Bechdel test score and the movie budget
 * Relationship between Bechdel test score and the movie gross profit 
 * Sub-analysis examining stratified relationship between Bechdel test score and movie   budget/profit per genre. 
 * Out of some of the most profitable films, how many pass the bechdel test
 * Trends between Bechdel test scores and metacritic review scores, and Bechdel test scores and IMDB review scores 

**Anticipated data sources:**
There are a number of datasets we intend to pull from: 

* [FiveThirtyEight](https://github.com/fivethirtyeight/data/blob/master/bechdel/movies.csv): This dataset describes movies released between 1990 - 2013 and contains variables on year of release, IMDB ID, title, Bechdel test type and pass/fail scores, budget, domestic gross revenue, international revenue, and budget (all monetary variables are presented in original amounts as well as adjusted for 2013 inflation)

* [The Movie Database](https://www.themoviedb.org/): This database contains up-to-date data regarding budget, rating, revenue, cast, and crew. Data can be accessed through an API

* [Bechdeltest.com](https://bechdeltest.com/): This database contains a running list of 9630 movies from 1874 to the present day (2022) and whether they pass the Bechdel test. Data can be accessed through an API 

**Planned analyses/visualizations/coding challenges:**
Planned analyses include correlation tests between Bechdel test scores and various indicators such as budget, gross profit, metacritic scores, IMDB scores, as well as stratified analyses by movie genre. We will also create visualizations for these analyses as well as for  the trend of movies passing the Bechdel test over time. 
Some challenges include cleaning and merging the datasets. We are pulling data from multiple sources and formats, we will have to tidy and combine the sources. We will also pull data from IMDB using CSS Selector. 

**Planned timeline**:

* 11/12 : Research proposal
* 11/18 : Review meeting
* 11/21 : Retrieve and merge datasets
* 11/24: Complete tidying dataset for analysis
* 11/27: Run analyses and analyze trends and correlations; Begin report writing
* 12/03: Finish report writing. Develop webpage and screencast
* 12/07 : Final edits


