---
title: "Sophia"
author: "Sophia Chkonia"
date: "2022-12-09"
output: html_document
---


```{r}
library(tidyverse)
library(plotly)
library(viridis)
library(shiny)
library(readr)
library(writexl)
install.packages('rsconnect')
library(rsconnect)

Superheroes = 
  readxl::read_excel("bechdel/Superheroes.xlsx") 
 

movies_df <- read_csv("non_website/Cathy/movies_df.csv")

View(movies_df)
```


## gathering additional dc movies from the movies_df dataframe

```{r}
DC_additional = 
  movies_df %>% 
  filter(title == "The Dark Knight" | title == "The Dark Knight Rises" | title == "Green Lantern" | title == "Batman Begins" | title == "Batman & Robin" | title == "Batman Forever" | title == "Batman Returns" ) %>% 
  mutate(
    domgross = domgross_2013,
    intgross = intgross_2013, 
    budget = budget_2013,
    totalgross = domgross_2013 + intgross_2013,
    universe = "DCEU",
    binary = pass_bechdel,
    binary = as.character(binary)
  ) %>% 
  select(title, year, domgross, intgross, budget, totalgross, binary, universe)


# combine with DCEU dataset

Superheroes_finally = bind_rows(Superheroes, DC_additional) %>% 
  mutate(binary = case_when(binary == "TRUE" ~ "PASS"))
  
write_xlsx(Superheroes_finally,path = "~/Desktop/Mailman/Semester 3/data science/final_project/non_website/Sophia\\Superheroes_final.xlsx")


```



```{r}

    
Superheroes_binary %>% 
  filter(title == "Thor") %>% 
  ifelse(binary == TRUE, plot(imageA), plot(imageB))




```


## previous dashboard graveyard

```{r}
titles = Superheroes %>%  distinct(title) %>% pull()

selectInput(
  inputId = "movie_choice",
  label = h3("Title"),
  choices = titles,
  selected = "Thor",
  
)


studios = Superheroes %>% distinct(universe) %>% pull()

checkboxGroupInput(
    inputId = "Studio_choice", 
    label = h3("Universe"), 
    choices = studios,
    selected = "MCU")
  
```

